version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.2.3
    - 11.2.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
  - dependency-name: karma
    versions:
    - 6.0.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
