image: 4tqrgqe5yrgfd/electron
stages:
  - build
  
before_script:
  - npm install
  - npm --prefix ./functions install
  
app-build-windows:
  stage: build
  artifacts:
    paths:
      - release/*.exe
  script:
    - npm run electron:windows
    
    
app-build-linux:
  stage: build
  artifacts:
    paths:
      - release/*.app
  script:
    - npm run electron:linux