image: 4tqrgqe5yrgfd/electron
stages:
  - build
  
before_script:
  - npm install
  - npm --prefix ./functions install
  
app-build:
  stage: build
  artifacts:
    paths:
      - release/*.exe
  script:
    - npm run electron:windows