# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: Windows
    displayName: Build windows
    pool:
      vmImage: windows-latest
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '12.x'

      - script: npm install
        displayName: 'npm install'

      - script: npm run electron:windows
        displayName: 'Run npm build'

      - task: CopyFiles@2
        displayName: 'Copy windows release'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/release/
          contents: '*.exe'
          targetFolder: '$(Build.ArtifactStagingDirectory)/windows'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'


  - job: Mac
    displayName: Build mac
    pool:
      vmImage: macOS-latest
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '12.x'

      - script: npm install
        displayName: 'npm install'

      - script: npm run electron:mac
        displayName: 'Run npm build'

      - task: CopyFiles@2
        displayName: 'Copy mac release'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/release/
          contents: '*.dmg'
          targetFolder: '$(Build.ArtifactStagingDirectory)/mac'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
