# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    # linux:
      # imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

# Windows
- script: |
    npm run electron:windows
  displayName: 'Build windows'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

# Mac
- script: |
    npm run electron:mac
  displayName: 'Build mac'
  condition: eq( variables['Agent.OS'], 'Darwin' )


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/release'
