name: 'Delete old artifacts'
on:
  schedule:
    - cron: '* 12 * * SUN,WED,FRI,' #  Runs at 02:00 UTC on Sun 

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
